Algoritmo "Atividade67"
//67) Faça um programa usando a estrutura “para” que leia um número inteiro
//positivo e mostre na tela uma contagem de 0 até o valor digitado:
//Ex: Digite um valor: 9
//Contagem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, FIM!

var
numero, zeroAte: inteiro

inicio
escreva ("Digite um número inteiro positivo: ")
leia (numero)

para zeroAte de 0 ate numero faca
escreva (zeroAte, "")
fimpara

escreva (" FIM!")

fimalgoritmo