Algoritmo "Atividade66"
//66) Escreva um programa que leia um número qualquer e mostre a tabuada desse
//número, usando a estrutura “para”.
//Ex: Digite um valor: 5
//5 x 1 = 5
//5 x 2 = 10
//5 x 3 = 15 ...

var
numero, umAdez: inteiro

inicio
escreva ("Digite um valor: ")
leia (numero)

para umAdez de 1 ate 10 faca
escreval (numero, " x ", umAdez, " = ", numero * umAdez)
fimpara

fimalgoritmo