Algoritmo "atividade13"

Var
km, precoTotal : real
dias : inteiro

Inicio
escreva ("Quantidade de Km percorridos: ")
   leia (km)
escreva ("Quantidade de dias alugado: ")
   leia (dias)

precoTotal <- (dias * 90) + (km * 0.20)
   escreval ("Preço do Aluguel")
   escreval ("Dias alugados: ", dias)
   escreval ("Km percorridos: ", km)
   escreval ("Preço total: R$", precoTotal)

Fimalgoritmo