Algoritmo "atividade10"

Var
largura, altura, areaPintada, tintaQntdd : real

Inicio
escreva ("Digite a largura da parede: ")
leia (largura)
escreva ("Digite a altura da parede: ")
leia (altura)

areaPintada <- largura * altura
tintaQntdd <- areaPintada / 2

escreval ("Área total a ser pintada: ", areaPintada, " m²")
escreva ("Quantidade de tinta necessária: ", tintaQntdd, " litros")
Fimalgoritmo