Algoritmo "questao06"

Var
num1, num2 : real

Inicio
escreva ("Digite o primeiro número: ")
leia (num1)

escreva ("Digite o segundo número: ")
leia (num2)

se (num1 > num2) entao
escreval ("O primeiro número (", num1, " ) é o maior.")
senao
se (num2 > num1) entao
escreval ("O segundo número (", num2, " ) é o maior.")
senao
escreval ("Ambos os números são iguais.")
fimse
fimse

Fimalgoritmo